name: Deploy to Server

on:
  push:
    branches: [ main ]

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build application
      run: npm run build
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: eu-central-1
        
    - name: Deploy to S3 (Ultra Aggressive Cache Busting)
      run: |
        echo "🧹 Ultra aggressive S3 bucket cleaning..."
        # Полная очистка S3 bucket
        aws s3 rm s3://trackista-live --recursive
        
        echo "⏳ Waiting for S3 cleanup to complete..."
        sleep 10
        
        echo "🚀 Deploying with timestamp-based cache busting..."
        TIMESTAMP=$(date +%s)
        
        # Синхронизируем все файлы заново с timestamp
        aws s3 sync dist/ s3://trackista-live --delete
        
        # Ultra aggressive no-cache для HTML файлов
        aws s3 cp dist/index.html s3://trackista-live/index.html \
          --cache-control "no-cache, no-store, must-revalidate, max-age=0, s-maxage=0, proxy-revalidate" \
          --expires "Thu, 01 Jan 1970 00:00:00 GMT" \
          --metadata-directive REPLACE \
          --metadata "timestamp=$TIMESTAMP"
        
        # Перезаписываем все assets с ultra aggressive no-cache
        aws s3 sync dist/assets/ s3://trackista-live/assets/ \
          --cache-control "no-cache, no-store, must-revalidate, max-age=0, s-maxage=0" \
          --expires "Thu, 01 Jan 1970 00:00:00 GMT" \
          --metadata-directive REPLACE
        
        echo "🔧 Configuring S3 for SPA routing with proper error handling..."
        
        # Проверяем, что файлы существуют
        echo "📋 Checking build files..."
        ls -la dist/
        
        # Создаем error.html как копию index.html для SPA routing
        if [ -f "dist/index.html" ]; then
          echo "✅ Found dist/index.html, setting up SPA routing..."
          aws s3 cp dist/index.html s3://trackista-live/error.html \
            --cache-control "no-cache, no-store, must-revalidate, max-age=0, s-maxage=0, proxy-revalidate" \
            --expires "Thu, 01 Jan 1970 00:00:00 GMT" \
            --metadata-directive REPLACE
        else
          echo "❌ dist/index.html not found! Build may have failed."
          exit 1
        fi
        
        # Настраиваем S3 для SPA (Single Page Application)
        aws s3 website s3://trackista-live --index-document index.html --error-document error.html
        
        # Дополнительно копируем index.html для всех возможных роутов
        echo "📁 Setting up SPA routing fallbacks..."
        aws s3 cp dist/index.html s3://trackista-live/density \
          --cache-control "no-cache, no-store, must-revalidate, max-age=0" \
          --metadata-directive REPLACE
        
        aws s3 cp dist/index.html s3://trackista-live/screener \
          --cache-control "no-cache, no-store, must-revalidate, max-age=0" \
          --metadata-directive REPLACE
          
        aws s3 cp dist/index.html s3://trackista-live/community \
          --cache-control "no-cache, no-store, must-revalidate, max-age=0" \
          --metadata-directive REPLACE
        
        echo "✅ Deployment completed with SPA routing support. Timestamp: $TIMESTAMP"